---
# file: tasks/install-postgres-exporter.yml
#
# Install Prometheus postgres-exporter.
#
# @see http://prometheus.io/docs/introduction/getting_started/
#

- block:

    - name: set internal variables for convenience
      set_fact:
        prometheus_postgres_exporter_subdir: "{{ prometheus_install_path }}/postgres_exporter-{{ prometheus_postgres_exporter_version }}.{{ prometheus_platform_suffix }}"

    - name: set download url for versions >= 0.2.2
      set_fact:
        prometheus_postgres_exporter_tarball_url: "https://github.com/wrouesnel/postgres_exporter/releases/download/v{{ prometheus_postgres_exporter_version }}/postgres_exporter"
      when: prometheus_postgres_exporter_version | version_compare('0.2.2', '>=')

    - name: set download url for versions < 0.2.2 (OBSOLETE!)
      set_fact:
        prometheus_postgres_exporter_tarball_url: "https://github.com/wrouesnel/postgres_exporter/releases/download/{{ prometheus_postgres_exporter_version }}/postgres_exporter"
      when: prometheus_postgres_exporter_version | version_compare('0.2.2', '<')

    - name: set daemon dir for versions >= 0.12
      set_fact:
        prometheus_postgres_exporter_daemon_dir: "{{ prometheus_postgres_exporter_subdir }}"
      when: prometheus_postgres_exporter_version | version_compare('0.2', '>=')

    - name: set daemon dir for versions < 0.12 (OBSOLETE!)
      set_fact:
        prometheus_postgres_exporter_daemon_dir: "{{ prometheus_install_path }}"
      when: prometheus_postgres_exporter_version | version_compare('0.2', '<')

    - name: Check postgres_exporter exist
      stat: path={{ prometheus_install_path }}/postgres_exporter-{{ prometheus_postgres_exporter_version }}.{{ prometheus_platform_suffix }}
      register: postgres_exporter_bin

    - name: Creates directory
      file: path="{{ prometheus_install_path }}/postgres_exporter-{{ prometheus_postgres_exporter_version }}.{{ prometheus_platform_suffix }}" state=directory

    - name: download and untar postgres_exporter tarball
      get_url:
        url: "{{ prometheus_postgres_exporter_tarball_url }}"
        dest: "{{ prometheus_install_path }}/postgres_exporter-{{ prometheus_postgres_exporter_version }}.{{ prometheus_platform_suffix }}/postgres_exporter"
        mode: 0755
      when: postgres_exporter_bin.stat.exists == False

  when: prometheus_postgres_exporter_version != "git"


- block:

    - name: set internal variables for convenience
      set_fact:
        prometheus_postgres_exporter_git_url: "https://github.com/wrouesnel/postgres_exporter.git"
        prometheus_postgres_exporter_src_path: "{{ prometheus_goroot }}/src/github.com/wrouesnel/postgres_exporter"
        prometheus_postgres_exporter_daemon_dir: "{{ prometheus_install_path }}"

    - name: delete the postgres_exporter build directory, if necessary
      file: path={{ prometheus_postgres_exporter_src_path }}  state=absent
      when: prometheus_rebuild

    - name: mkdir for postgres_exporter source code
      file: path={{ prometheus_postgres_exporter_src_path }}  state=directory

    - name: clone the postgres_exporter project src
      git:
        repo: "{{ prometheus_postgres_exporter_git_url }}"
        dest: "{{ prometheus_postgres_exporter_src_path }}"
        force: yes

    - name: build postgres_exporter source code
      command: make
      args:
        chdir: "{{ prometheus_postgres_exporter_src_path }}"
        creates: postgres_exporter
      environment:
        GO15VENDOREXPERIMENT: 1
        GOROOT: "{{ prometheus_goroot }}"
        GOPATH: "{{ prometheus_gopath }}"
        PATH: "{{ ansible_env.PATH }}:{{ prometheus_goroot }}/bin:{{ prometheus_gopath }}/bin"

    - name: copy the built postgres_exporter to the install path
      command: "cp {{ prometheus_postgres_exporter_src_path }}/postgres_exporter {{ prometheus_install_path }}"
      args:
        creates: "{{ prometheus_install_path }}/postgres_exporter"

  when: prometheus_postgres_exporter_version == "git"



- name: set permissions, owner and group
  file: path={{ prometheus_postgres_exporter_daemon_dir }}/postgres_exporter owner={{ prometheus_user }} group={{ prometheus_group }} mode="go-w"
  when: postgres_exporter_bin.stat.exists == False

- name: mkdir for data
  file:
    path: "{{ prometheus_db_path }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "u=rwx,g=rx,o="

- name: set postgres_exporter variables
  copy: src="../files/etc-default-postgres_exporter"  dest=/etc/default/postgres_exporter
  register: postgres_exporter_config

- debug: var=postgres_exporter_config
  notify: reload postgres_exporter
  when: postgres_exporter_config.changed


- name: copy INIT script to server
  template: src="../templates/postgres_exporter.sysvinit.{{ ansible_os_family|lower }}.sh.j2"  dest="/etc/init.d/postgres_exporter"  mode="a+x"
  when: not prometheus_postgres_exporter_use_systemd|bool

- name: copy systemd config to server
  template: src="../templates/postgres_exporter.service.j2"  dest="/lib/systemd/system/postgres_exporter.service"
  when: prometheus_postgres_exporter_use_systemd|bool


- name: set INIT status and start
  service: name=postgres_exporter enabled=yes state=started
  when: postgres_exporter_bin.stat.exists == False
